# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Brandon Chaperon
tagline:          'tagline'
description:      'McGill Linguistics Grad Student'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Brandon Chaperon'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
