# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Brandon Chaperon
tagline:          'tagline'
description:      'McGill Linguistics Grad Student'
url:              https://bchap.ca
baseurl:          /

author:
  name:           'Brandon Chaperon'
  email:          'brandon [dot] chaperon [at] mail [dot] mcgill [dot] ca'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
