# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            brandon chaperon
tagline:          ''
description:      'recent mcgill linguistics grad'
url:              https://bchap.ca/
baseurl:          /

author:
  name:           'brandon chaperon'
  email:          
    name:         '@norepahc.nodnarb'
    domain:       'ac.lligcm.liam'

# Custom vars
version:          1.0.0
